### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by VargaDot** [VargaDot/CapMan#11]
# Tasks

- [ ] Add a score system
- [ ] Add a highscore system
- [ ] Add kill count

# Optional

- [ ] Add steps count
