### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by VargaDot** [VargaDot/CapMan#5]
# Tasks

- [x] #10
- [ ] Make a "play button pressed" animation for the instruction
- [ ] Animate the player
- [ ] Animate the chasers
- [ ] Animate the scene transition
